#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config \
	active_window_opacity 1.0 \
	auto_balance on \
	bottom_padding 12 \
	left_padding 12 \
	right_padding 18 \
	top_padding 12 \
	window_gap 12 \
	debug_output on \
	display_arrangement_order default \
	external_bar off:40:0 \
	focus_follows_mouse off \
	insert_feedback_color 0xffd75f5f \
	layout bsp \
	menubar_opacity 1.0 \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	mouse_follows_focus on \
	mouse_modifier cmd \
	normal_window_opacity 0.70 \
	split_ratio 0.50 \
	split_type auto \
	window_animation_duration 0.0 \
	window_animation_easing ease_out_circ \
	window_opacity off \
	window_opacity_duration 0.0 \
	window_origin_display default \
	window_placement second_child \
	window_shadow on \
	window_zoom_persist on

yabai -m rule --add label="1Password" app='^1Password$' manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Alfred" app="^Alfred Preferences$" manage=off
yabai -m rule --add label="AnyBox" app="^Anybox$" manage=off
yabai -m rule --add label="Apple TV" app="^TV$" manage=off # Problem
yabai -m rule --add label="Audio MIDI Setup" app="^Audio MIDI Setup$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Cardhop" app="^Cardhop$" manage=off
yabai -m rule --add label="Chronosync" app="^ChronoSync$" manage=off
yabai -m rule --add label="CitrixV" app='^Citrix Viewer$' manage=off
yabai -m rule --add label="CitrixWS" app='^Citrix Workspace$' manage=off
yabai -m rule --add label="CleanMyMac" app="^CleanMyMac$" manage=off
yabai -m rule --add label="Coin Stats" app="^Coin Stats$" manage=off
yabai -m rule --add label="Console" app="^Console$" manage=off
yabai -m rule --add label="Contacts" app="^Contacts$" manage=off
yabai -m rule --add label="DEVONagent Pro" app="^DEVONagent Pro$" manage=off
yabai -m rule --add label="Daisy Disk" app="^DaisyDisk$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Discord" app="^Discord$" manage=off
yabai -m rule --add label="Disk Utility" app="^Disk Utility$" manage=off
yabai -m rule --add label="Docker Desktop" app="^Docker Desktop$" manage=off
yabai -m rule --add label="FaceTime" app="^FaceTime$" manage=off
yabai -m rule --add label="Find My" app="^Find My$" manage=off
yabai -m rule --add label="Finder" app='^Finder$' manage=off
yabai -m rule --add label="Folder Marker" app="^FolderMarker$" manage=off
yabai -m rule --add label="Font Book" app="^Font Book$" manage=off
yabai -m rule --add label="Habits" app="^Habits$" manage=off
yabai -m rule --add label="Ice" app="^Ice$" manage=off
yabai -m rule --add label="iStat Menus" app="^iStat Menus$" manage=off
yabai -m rule --add label="Karabiner-Elements" app="^Karabiner-Elements$" manage=off
yabai -m rule --add label="Karabiner-EventViewer" app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add label="Keyboard Maestro" app="^Keyboard Maestro$" manage=off
yabai -m rule --add label="LuLu" app="^LuLu$" manage=off
yabai -m rule --add label="Mail" app="^Mail$" manage=off
yabai -m rule --add label="Messages" app="^Messages$" manage=off
yabai -m rule --add label="Notes" app="^Notes$" manage=off
yabai -m rule --add label="OnlySwitch" app="^OnlySwitch$" manage=off
yabai -m rule --add label="PCalc" app="^PCalc$" manage=off
yabai -m rule --add label="Parallels Desktop" app="^Parallels Desktop$" manage=off
yabai -m rule --add label="Passwords" app="^Passwords$" manage=off
yabai -m rule --add label="PathFinder" app='^Path Finder$' manage=off
yabai -m rule --add label="Photo Booth" app="^Photo Booth$" manage=off
yabai -m rule --add label="Podcasts" app="^Podcasts$" manage=off
yabai -m rule --add label="Preview" app="^Preview$" manage=off
yabai -m rule --add label="QMK Toolbox" app="^QMK Toolbox$" manage=off
yabai -m rule --add label="RealVNC" app="^VNC Viewer$" manage=off
yabai -m rule --add label="Reminders" app="^Reminders$" manage=off
yabai -m rule --add label="SF Symbols" app="^SF Symbols$" manage=off
yabai -m rule --add label="Setapp" app="^Setapp$" manage=off
yabai -m rule --add label="Settings" app='^System Settings$' manage=off
yabai -m rule --add label="Shortcuts" app="^Shortcuts$" manage=off
yabai -m rule --add label="Spark Mail" app="^Spark Mail$" manage=off
yabai -m rule --add label="Tot" app="^Tot$" manage=off
yabai -m rule --add label="TradingView" app='^TradingView$' manage=off
yabai -m rule --add label="Transmission" app='^Transmission$' manage=off
yabai -m rule --add label="VLC" app="^VLC$" manage=off
yabai -m rule --add label="WhatsApp" app="WhatsApp" title="WhatsApp" manage=off
yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --apply

echo "yabai configuration loaded.."
