#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"
source "$HOME/.config/sketchybar/icon_map.sh"

HELPER="$HOME/.config/sketchybar/helper/helper"

FONT="SF Pro"

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

PADDINGS=3

sketchybar --bar height=50 \
  shadow=on \
  position=right \
  sticky=on \
  padding_right=18 \
  padding_left=18 \
  corner_radius=9 \
  y_offset=10 \
  margin=10 \
  blur_radius=20 \
  \
  --default updates=when_shown \
  icon.font="$FONT:Bold:14.0" \
  icon.color="$ICON_COLOR" \
  icon.padding_left=$PADDINGS \
  icon.padding_right=$PADDINGS \
  label.font="$FONT:Semibold:13.0" \
  label.color="$LABEL_COLOR" \
  label.padding_left=$PADDINGS \
  label.padding_right=$PADDINGS \
  background.padding_left=$PADDINGS \
  background.padding_right=$PADDINGS \
  popup.background.border_width=2 \
  popup.background.corner_radius=11 \
  popup.background.border_color="$POPUP_BORDER_COLOR" \
  popup.background.color="$POPUP_BACKGROUND_COLOR" \
  popup.background.shadow.drawing=on

# source "$HOME/.config/sketchybar/plugins/apple.sh"

source "$HOME/.config/sketchybar/plugins/aerospace.sh"

# source "$HOME/.config/sketchybar/plugins/cpu.sh"
#
# source "$HOME/.config/sketchybar/plugins/github.sh"
#
# source "$HOME/.config/sketchybar/plugins/calendar.sh"

sketchybar --update
sketchybar --hotload on

echo "sketchybar configuration loaded.."
