#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config \
  active_window_opacity 1.0 \
  auto_balance on \
  bottom_padding 12 \
  debug_output on \
  display_arrangement_order default \
  external_bar off:40:0 \
  focus_follows_mouse off \
  insert_feedback_color 0xffd75f5f \
  layout bsp \
  left_padding 12 \
  menubar_opacity 1.0 \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  mouse_follows_focus off \
  mouse_modifier fn \
  normal_window_opacity 0.90 \
  right_padding 12 \
  split_ratio 0.50 \
  split_type auto \
  top_padding 12 \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  window_gap 06 \
  window_opacity off \
  window_opacity_duration 0.0 \
  window_origin_display default \
  window_placement second_child \
  window_shadow on \
  window_zoom_persist on

yabai -m rule --add label="Settings" app='^System Settings$' manage=off
yabai -m rule --add label="Finder" app='^Finder$' manage=off
yabai -m rule --add label="1Password" app='^1Password$' manage=off
yabai -m rule --add label="Transmission" app='^Transmission$' manage=off
yabai -m rule --add label="CitrixWS" app='^Citrix Workspace$' manage=off
yabai -m rule --add label="CitrixV" app='^Citrix Viewer$' manage=off
yabai -m rule --add label="TradingView" app='^TradingView$' manage=off
yabai -m rule --add label="PathFinder" app='^Path Finder$' manage=off

echo "yabai configuration loaded.."
